name: Deploy to Firebase Hosting (Static)

on: 
  push:
    branches:
      - master # Explicitly set to master to match your push branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Updated to Node.js 20

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installs in CI environments

      - name: Build Next.js Static App
        run: npm run build
      - run: npm run build
        env:
          FIREBASE_PROJECT_ID: ${{ "automation-4e6bd" }}
          FIREBASE_CLIENT_EMAIL: ${{ "firebase-adminsdk-fbsvc@automation-4e6bd.iam.gserviceaccount.com" }}
          FIREBASE_PRIVATE_KEY: ${{ "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDCM8obceryKGCW\nz7Qp8zX5YTavP4DacvQZYpqEdbSDlz/2kTPVFCgLaO7dbffZay9dtP8FJsBrMYXf\nf+49mWXS8auN4H3hCwB3Ora9SLr51AWxK7VfBRERoDNOe+fKTXWgtQGpaRCUhhMt\nBe+mRegUfzS+FsV2tpPYk3ZZI73X+N/FjnWb2I1rlg+3v9S/fEIxWQfEIyLaEqTF\n8LlC1cYxMQ4Eqg597JXDsYV399ZQ7UCWxHs/06b51Fq3VB0+6HM7xMqDfWDd/5WL\ngQ/VmR11SO1xzbPMbOLxvNvolkrJGnW7B6CK/w0ZURZE+zQI50ZZSOpw0mqPUDed\nlNqY0Yk9AgMBAAECggEAARk/Z7PXhyqszzWaGJGoaMKAx3GFxlaXpGwfISg0TvlE\nUp4EK8yrJFNh5I1KdWeqky5isfID7SdQ0VCdNaqAPbcByDHwrFz+Ue5aWcxHSIIH\nTTcI1eKGs/GS0LsZNtcE1xWnDoEKZ7ixc5QAxNFI7JLCpt+kmtUSFYvSA9OUr5vV\njGlEYG6m9Uqp5TZPzSEjG+BHR22a83AswS7C79u5KioD53ZQSXECSvLc5vNo0iYA\nal5koFn00hKJiI/HWTowlMJB2X9EvPU4s3/Vkww2hSd8wbtNSfS6YzLNN0Oe9a66\nx3bSCNXSAmQ29solzeW5/8KsNPhZ5K/aFBDYAvjvsQKBgQDfCvsKyNXYBMJPcWWH\n+1amLUF0LxfF+Vv/giK0NpKPolkkJZdCuvVxwawEzkHEZcxH0evATq8B+Oq2IujU\ncU82FxY0yB5F7CiwnjxQiDEpNoj9Xm6Q1ukwL7GmKzFVNjRpYB8cVkUz4zkXt8sy\nmZVXdw8v2PindOdAWPdtSCigTQKBgQDe5dvkjvonMvTD/FO7HOrs95GDjujr88ms\ncNkoWlmjY2QJTetwRJLbiRPu7NGsuKw8AkKNM1+QGKkCPu2BEvdzYeb1MIBCUaxR\nsxHx9mDUZssMD+DvVty1DYWoqU9mQn+JX4AUlX6+/7xCN31GoCatH4+LioTA1TEG\nhAV3G9+EsQKBgDRFf4YMgUlJ/DvgCHpw5eK2EnPnIXwtL2lXF0kCzSBKXPfCs4tZ\nA3Kwf970c6dScCiYwtZj2lHtAxzCW6yGDZlQmcyu5aFfcj3KJ7p74IGXHU271s+s\n/iNj2g9maf5dYLUdaM0cTsWVR+kOEtn98mj4JyAAim28UQHcl8gNtC+1AoGAOXON\npe+kUo4zwIA9JLFjbAiznPEs4ARKKwQ7NMd060Qm+K74zEsgfy1p0d+Ae8BtxFng\nxXxEWWPBzC5kESzOUxMc8H270VwzyisZqQAUHSsRkt5U39vHr3L4zGw3Zugk70eK\nP8P4k0pfP8IFrDqDPYQw/4qIhRtuM3u73ON2TUECgYEAzy1xUTekWCSgUBd8W6fr\nlGHdpfxNug5XnyJrT2RLFjWggvyVw1R0jj3KbSAWVnkW2DGaZTYpcoU91T9OswUj\nhcLTT78VzNKi9oT3OGpjA5g1dTV4jpC5+COLrA83iQhL2KCZCBV0bwf2oVNx5tfN\nlz74KfAI+tM6EMPZS2Wfy+I=\n-----END PRIVATE KEY-----\n", }}

        
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          projectId: 'automation-4e6bd'
          channelId: 'live' # Deploys to the live channel
          # Make sure your firebase.json has "public": "out"
